#webserver
server:
  port: 8080
#spring
spring:
  application:
    name: GraduationDesign
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: He11()W0r1d
    url: jdbc:mysql://59.110.230.101:3306/school?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 连接池的配置信息
#    # 初始化大小，最小，最大
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    #配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1 from dual
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,log4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

 # thymeleaf start
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


debug: false




